site_name: The Documentation
theme:
  favicon: assets/droplet.svg
  icon:
    logo: fontawesome/solid/droplet
  font:
    text: Inter
    code: JetBrains Mono
  name: material
  palette:
    scheme: slate
    primary: blue grey

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg